### ISSUE TITLE
How to specify what in the header or elsewhere should be available on top of the text?

### ISSUE THREAD

**Issue by PonteIneptique** [Capitains/website#13]
This is stricto sensu not the most important thing ever. But right now, we do not support any header sending, when I believe people would be interested to do so. Example : list of authorities. 

To do so, I'd propose a refsDecl "capitains-adendum" with cRefPattern representing the xpath which shall be transported,

**Comment by balmas** [comment]
Is the discussion we had with @nevenjovanovic about headers in Krakow relevant to this?

**Comment by nevenjovanovic** [comment]
What I had in mind (and perhaps I should open a separate issue) is that elements which are not `p` or `l` , but are equally children of `div`, ought to have a CTS URN; `head` is the most common one, but there are also `opener` and `closer`, etc. Having stuff from the header (or `teiHeader`) addressed by CTS URN is something else.

**Comment by PonteIneptique** [comment]
Well you can already do what Neven is saying, so it's fine. :)

**Comment by PonteIneptique** [comment]
Close because it's relevant to Github.com/capitains/guidelines now
